apiVersion: v1
kind: Service
metadata:
  name: game-tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: game-tcp
    protocol: TCP
    port: 3979
    targetPort: 3979
---
apiVersion: v1
kind: Service
metadata:
  name: game-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: advertise-udp
    protocol: UDP
    port: 3978
    targetPort: 3978
  - name: game-udp
    protocol: UDP
    port: 3979
    targetPort: 3979