apiVersion: v1
kind: Service
metadata:
  name: openttd
  labels:
    app: openttd
spec:
  clusterIP: None
  selector:
    app: openttd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: game-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: game-save
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openttd
spec:
  selector:
    matchLabels:
      app: openttd
  serviceName: openttd
  template:
    metadata:
      labels:
        app: openttd
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3.6
        command:
        - chown
        - -R
        - 911:911
        - /config
        volumeMounts:
        - name: game-save
          mountPath: /config/save
        - name: game-config
          mountPath: /config
      containers:
      - name: openttd
        image: redditopenttd/openttd:latest
        imagePullPolicy: Always
        env:
          - name: BAN_LIST
            value: "bans.txt"
          - name: COPY_CONFIG
            value: "/k8s/config"
        ports:
        - containerPort: 3979
          protocol: TCP
          name: game-tcp
        - containerPort: 3979
          protocol: UDP
          name: game-udp
        - containerPort: 3978
          protocol: UDP
          name: advertise-udp
        volumeMounts:
        - name: game-save
          mountPath: /config/save
        - name: game-config
          mountPath: /config
        - name: game-configmap
          mountPath: /k8s/config
      - name: bans-sidecar
        image: redditopenttd/bans-sidecar:latest
        volumeMounts:
        - name: game-config
          mountPath: /config
      volumes:
      - name: game-config
        persistentVolumeClaim:
          claimName: game-config
      - name: game-save
        persistentVolumeClaim:
          claimName: game-save
      - name: game-configmap
        configMap:
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: openttd-nodeport
  labels:
    app: openttd
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: game-tcp
    protocol: TCP
    port: 3979
    targetPort: 3979
    nodePort: 3979
  - name: advertise-udp
    protocol: UDP
    port: 3978
    targetPort: 3978
    nodePort: 3978
  - name: game-udp
    protocol: UDP
    port: 3979
    targetPort: 3979
    nodePort: 3979
  selector:
    app: openttd