apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  serviceName: game
  template:
    metadata:
      labels:
        app: game
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3.6
        command:
        - chown
        - -R
        - 911:911
        - /config
        volumeMounts:
        - name: game-save
          mountPath: /config/save
        - name: game-config
          mountPath: /config
      containers:
      - name: openttd
        image: redditopenttd/openttd:latest
        imagePullPolicy: Always
        env:
          - name: BAN_LIST
            value: "bans.txt"
          - name: COPY_CONFIG
            value: "/k8s/config"
        ports:
        - containerPort: 3979
          protocol: TCP
          name: game-tcp
        - containerPort: 3979
          protocol: UDP
          name: game-udp
        - containerPort: 3978
          protocol: UDP
          name: advertise-udp
        - containerPort: 3977
          protocol: TCP
          name: admin-tcp
        volumeMounts:
        - name: game-save
          mountPath: /config/save
        - name: game-config
          mountPath: /config
        - name: game-configmap
          mountPath: /k8s/config
      - name: bans-sidecar
        image: redditopenttd/bans-sidecar:latest
        volumeMounts:
        - name: game-config
          mountPath: /config
      volumes:
      - name: game-config
        persistentVolumeClaim:
          claimName: game-config
      - name: game-save
        persistentVolumeClaim:
          claimName: game-save
      - name: game-configmap
        configMap:
          name: config
  volumeClaimTemplates:
    - metadata:
        name: game-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
        storageClassName: local-path
    - metadata:
        name: game-save
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path