apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  serviceName: game
  template:
    metadata:
      labels:
        app: game
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3.6
        command:
          - chown
          - -R
          - 911:911
          - /config
        volumeMounts:
          - name: game-save
            mountPath: /config/save
          - name: game-config
            mountPath: /config
      - name: openttd-init
        image: redditopenttd/k8s-helper:latest
        args:
          - -origin-config=/k8s/config/openttd.cfg
          - -destination=/config
          - -merge-bans=/config/bans.txt
          - -sync-newgrfs
        volumeMounts:
          - name: game-config
            mountPath: /config
          - name: game-configmap
            mountPath: /k8s/config
      containers:
      - name: openttd
        image: redditopenttd/openttd:latest
        imagePullPolicy: Always
        resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 500Mi
              cpu: "500m"
        ports:
        - containerPort: 3979
          protocol: TCP
          name: game-tcp
        - containerPort: 3979
          protocol: UDP
          name: game-udp
        - containerPort: 3978
          protocol: UDP
          name: advertise-udp
        - containerPort: 3977
          protocol: TCP
          name: admin-tcp
        volumeMounts:
        - name: game-save
          mountPath: /config/save
        - name: game-config
          mountPath: /config
        livenessProbe:
          tcpSocket:
            port: game-tcp
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: bans-sidecar
        image: redditopenttd/bans-sidecar:latest
        resources:
            limits:
              memory: 50Mi
              cpu: "50m"
            requests:
              memory: 10Mi
              cpu: "5m"
        volumeMounts:
        - name: game-config
          mountPath: /config
      volumes:
      - name: game-config
        persistentVolumeClaim:
          claimName: game-config
      - name: game-save
        persistentVolumeClaim:
          claimName: game-save
      - name: game-configmap
        configMap:
          name: config
  volumeClaimTemplates:
    - metadata:
        name: game-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
        storageClassName: local-path
    - metadata:
        name: game-save
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path