name: Build and Push Latest Versions

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'

env:
  IMAGE_NAME: redditopenttd/openttd

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Discover upstream version
        uses: ropenttd/cdn_version_scraper@master
        with:
          channel: 'stable'
        id: version

      - name: Build image
        run: docker build . --file Dockerfile --build-arg OPENTTD_VERSION=${{ steps.version.outputs.version }} --tag $IMAGE_NAME

      - name: Log into Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        run: |
          echo Tagging for stable version ${{ steps.version.outputs.version }}

          for t in latest stable ${{ steps.version.outputs.version }}; do
              docker tag $IMAGE_NAME $IMAGE_NAME:${t}
              docker push $IMAGE_NAME:${t}
          done

  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Discover upstream version
        uses: ropenttd/cdn_version_scraper@master
        with:
          channel: 'testing'
        id: version

      - name: Build image
        run: docker build . --file Dockerfile --build-arg OPENTTD_VERSION=${{ steps.version.outputs.version }} --tag $IMAGE_NAME

      - name: Log into Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        run: |
          echo Tagging for testing version ${{ steps.version.outputs.version }}

          for t in testing rc beta ${{ steps.version.outputs.version }}; do
              docker tag $IMAGE_NAME $IMAGE_NAME:${t}
              docker push $IMAGE_NAME:${t}
          done